

GET  http://localhost:3000/api/services/all
Content-Type: application/json


###


POST http://localhost:3000/api/services/add
Content-Type: application/json

{
      "name": "webcluster",
      "displayName": "Web Cluster",
      "description": "Web cluster"
}


###


POST http://localhost:3000/api/incidents/add
Content-Type: application/json

{
      "service": "webcluster",
      "status": 200,
      "description": "Web cluster",
      "issuedAt": "2021/1/30"
}

###

DELETE  http://localhost:3000/api/services/remove
Content-Type: application/json

